# Generated by Django 5.2.6 on 2025-09-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('K', 'Kids'), ('M', 'Mens'), ('W', 'Womens')], max_length=1)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
