# Generated by Django 5.2.6 on 2025-09-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_latestnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnews',
            name='text',
        ),
        migrations.AddField(
            model_name='latestnews',
            name='description',
            field=models.TextField(blank=True, help_text='The full description of the news', null=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='title',
            field=models.CharField(default='', help_text='The title of the news', max_length=255),
        ),
    ]
