# Generated by Django 5.2.6 on 2025-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_latestnews_text_latestnews_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
